description "CapStash Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env CAPSTASHD_BIN="/usr/bin/CapStashd"
env CAPSTASHD_USER="CapStash"
env CAPSTASHD_GROUP="CapStash"
env CAPSTASHD_PIDDIR="/var/run/CapStashd"
# upstart can't handle variables constructed with other variables
env CAPSTASHD_PIDFILE="/var/run/CapStashd/CapStashd.pid"
env CAPSTASHD_CONFIGFILE="/etc/CapStash/CapStash.conf"
env CAPSTASHD_DATADIR="/var/lib/CapStashd"

expect fork

respawn
respawn limit 5 120
kill timeout 600

pre-start script
    # this will catch non-existent config files
    # CapStashd will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$CAPSTASHD_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run CapStashd."
        echo "The setting must appear in $CAPSTASHD_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following "
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"CapStash Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$CAPSTASHD_PIDDIR"
    chmod 0755 "$CAPSTASHD_PIDDIR"
    chown $CAPSTASHD_USER:$CAPSTASHD_GROUP "$CAPSTASHD_PIDDIR"
    chown $CAPSTASHD_USER:$CAPSTASHD_GROUP "$CAPSTASHD_CONFIGFILE"
    chmod 0660 "$CAPSTASHD_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$CAPSTASHD_PIDFILE" \
    --chuid $CAPSTASHD_USER:$CAPSTASHD_GROUP \
    --exec "$CAPSTASHD_BIN" \
    -- \
    -pid="$CAPSTASHD_PIDFILE" \
    -conf="$CAPSTASHD_CONFIGFILE" \
    -datadir="$CAPSTASHD_DATADIR" \
    -disablewallet \
    -daemon

